title: Frederick John
name: Frederick John
author: FJ
description: >-
  A blog covering the musings and interests of FJ
baseurl: ""
url: "https://essenceofchaos.github.io/"
twitter_username: webteamu
github_username:  EssenceOfChaos

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
exclude: [priv]
exclude: [priv, README.md, node_modules]
encoding: utf-8
timezone: America/New_York

source: _site
destination: src


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/